version: '3.8'

services:

  php:
    build: ./src_php
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src_php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10

  db-init:
    image: mysql:8.0
    container_name: db_init
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database:/database
    command: >
      bash -c "
        chmod +x /database/init-db.sh &&
        /database/init-db.sh
      "
    restart: "no"

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  db_data: